site_name: Vimeo Monitor
site_description: Monitor Vimeo live streams on Raspberry Pi
site_author: Vimeo Monitor Team
site_url: https://pcommcapp.github.io/vimeo-monitor/
repo_url: https://github.com/PiCommCapp/vimeo-monitor
repo_name: PiCommCapp/vimeo-monitor
edit_uri: edit/main/docs/

# Configuration
theme:
  name: readthedocs

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree - Enhanced navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Quick Start: quick-start.md
  - User Guide:
    - Basic Usage: usage.md
    - Troubleshooting: troubleshooting.md
    - Health Monitoring: health-monitoring.md
  - Development:
    - API Reference: api-reference.md
    - Contributing: contributing.md
    - Development Setup: development.md
  - Project:
    - Architecture: architecture.md
    - Changelog: changelog.md
    - License: license.md

# Note: Memory bank, archive, and other non-documentation files
# are excluded from the documentation build by not including them
# in the navigation structure above.