site_name: Vimeo Monitor
site_description: Monitor Vimeo live streams on Raspberry Pi
site_author: Vimeo Monitor Team

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree - Simple 3-page structure
nav:
  - Home: index.md
  - Installation: installation.md
  - Troubleshooting: troubleshooting.md

# Exclude memory bank and decision documents
exclude_docs: |
  memory_bank/
  *.decision.md
  *.plan.md