[project]
name = "vimeo-monitor"
version = "0.0.2"
description = "Lint your n8n JSON here."
readme = "README.md"
authors = [
  {name = "Dom Capparelli", email = "web@Capparelli.ie"}
]
maintainers = [
  {name = "Dom Capparelli", email = "web@Capparelli.ie"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Vimeo",
  "Topic :: Software Development :: Monitoring",
]
license = "MIT"

dependencies = [
  "pyvimeo>=1.1.2",
  "python-dotenv>=1.0.0",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
]

[project.optional-dependencies]
test = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
vimeo_monitor = ["*.py"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pre-commit>=4.2.0",

    "pytest-cov>=6.1.1",
    "ruff>=0.11.11",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "mkdocstrings[python]>=0.29.1",
    "pyinstaller>=6.13.0",
]

test = [
    "coverage",  # testing
    "pytest",  # testing
    "ruff",  # linting
    "mypy", # checking types
    "ipdb", # debugging
]

security = [
    "safety>=3.0.0",  # security vulnerability scanner
    "bandit>=1.7.0",  # security linter
]

[project.urls]
bugs = "https://github.com/PiCommCapp/vimeo-monitor/issues"
changelog = "https://github.com/PiCommCapp/vimeo-monitor/blob/master/changelog.md"
homepage = "https://github.com/PiCommCapp/vimeo-monitor"

[tool.ruff]
target-version = "py312"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true

[tool.uv]
package = true
