version: 2
updates:
  # Python dependencies managed by UV
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # UV-specific configuration
    target-branch: "main"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
