name: Test Documentation Build

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/test-docs-build.yml'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  test-docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Setup UV
        uses: astral-sh/setup-uv@v2
        
      - name: Install dependencies
        run: uv pip install mkdocs mkdocs-material pymdown-extensions
        
      - name: Test documentation build
        run: uv run mkdocs build --strict
        
      - name: Verify site directory
        run: |
          if [ ! -d "./site" ]; then
            echo "Documentation build failed - site directory not found"
            exit 1
          fi
          echo "Documentation build successful"
